// Code generated by "stringer -type=instantDecision"; DO NOT EDIT.

package main

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[decisionNone-0]
	_ = x[decisionBan-1]
	_ = x[decisionWhitelist-2]
}

const _instantDecision_name = "decisionNonedecisionBandecisionWhitelist"

var _instantDecision_index = [...]uint8{0, 12, 23, 40}

func (i instantDecision) String() string {
	if i < 0 || i >= instantDecision(len(_instantDecision_index)-1) {
		return "instantDecision(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _instantDecision_name[_instantDecision_index[i]:_instantDecision_index[i+1]]
}
