on:
  push:
    tags:
      - '*'
    branches:
      - '*'

jobs:
  tests:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: '1.18.x'
      - env:
          GO111MODULE: on
        run: go test
  build_publish:
    needs: tests
    if: github.event_name == 'push' && contains(github.ref, 'refs/tags/') # run only on tags
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: '1.18.x'
      - name: build
        env:
          CGO_ENABLED: 0
          GO111MODULE: on
        run: go build -o botassasin
      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: botassasin
          asset_name: botassasin
          tag: ${{ github.ref }}
